export const SELECTED_CHOOSE_FORM_VALUES = 'SELECTED_CHOOSE_FORM_VALUES';
export const SELECTED_CREATE_CHAR_VALUES = 'SELECTED_CREATE_CHAR_VALUES';
export const SELECTED_CONTACT_FORM_VALUES = 'SELECTED_CONTACT_FORM_VALUES';
